### ISSUE TITLE
error in example.md? index.html?

### ISSUE THREAD

**Issue by ooiikkjj** [ondras/maslo#4]
keep getting this error in the example subdir...no matter what i do...

![image](https://user-images.githubusercontent.com/75536247/105952408-8970a880-603f-11eb-9141-39ff382caacc.png)

**Comment by ondras** [comment]
Okay, and what does the console say?

(Open your browser's devtools console - often via the F12 key.)

**Comment by ooiikkjj** [comment]
muddled my way into making it work...thanks!

**Comment by ondras** [comment]
👍
